spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pretest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
api-key:
  kakao: "0d65264c6e20efd91796180fce279c1e"